In [1]:
lis = []

In [3]:
max([m for m in lis])

ValueError: max() iterable argument is empty

In [6]:
import numpy as np
np.max([])

ValueError: zero-size array to reduction operation maximum which has no identity

In [1]:
import os
path = "/Users/gh478/Documents/Research/multispectral-analysis/test/msa_utils.py"


In [9]:
basename = os.path.splitext(os.path.basename(path))[0]
basename.replace("_", "")

'msautils'

In [21]:
import numpy as np

In [ ]:
test = np.array([1, 2, 3])
test2 = np.array([4, 5, 0])
var = 
np.divide(test, var, out=np.zeros(test), where=var!=0)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
# create two 2D test arrays
a = np.array([[1, 2, 1], [4, 5, 6]])
b = np.array([[1, 1, 2], [2, 2, 2]])
np.where(a >= b, a, 0)

array([[1, 2, 0],
       [4, 5, 6]])

In [14]:
def group_strlist(self, strlist: list[str]) -> dict[str, list[str]]:
    """
    Groups strings in strlist by common substrings separated by underscores.
    Returns a dictionary mapping substrings to lists of strings containing them.
    """
    groups = dict()
    groups_idx = []
    count = 0
    for i, s in enumerate(strlist):
        if s not in groups.keys():
            count += 1
            groups[s] = count
        groups_idx.append(groups[s])

    return groups_idx

test = ['aaa', 'aaa', 'bbb', 'aaa', 'bbb', 'ccc', 'ccc']
test = np.array(group_strlist(None, test))

In [1]:
test = [1,2,3]
test2 = test.copy()
test2

[1, 2, 3]

In [22]:
np.unique(test)

array([1, 2, 3])