In [1]:
import numpy as np

In [1]:
import h5py
path = "/Users/gh478/Documents/Research/multispectral-analysis/hdf5_data.h5"
f = h5py.File(path, 'r')

In [6]:
groups_idx = np.array([0, 0, 1, 1, 2, 2])
group_idx = 1
np.where(groups_idx == group_idx)[0]

array([2, 3])

In [2]:
for key in f.keys():
    print(f"Group {key}: {list(f[key].keys())}")

Group 2: ['hey', 'ones', 'threes', 'twos']
Group default: ['1']


In [5]:
f['default']['1'][()]

b'/Users/gh478/Documents/Research/multispectral-analysis/src/data/cross.csv'

In [6]:
f.close()

In [10]:
test = [0, 2, 3, 1, 1]
for t in test:
    print(t)
for t in set(test):
    print(t)
test = set(test)
test.discard(2)
test


0
2
3
1
1
0
1
2
3


{0, 1, 3}

In [ ]:
# Create example numpy array
arr = np.random.randint(0, 10, size=(10,))


array([3, 6, 7, 9])

In [16]:
for val, count in zip(values, counts):
    print(f"Value: {val}, Count: {count}")

Value: 2, Count: 2
Value: 3, Count: 1
Value: 5, Count: 4
Value: 6, Count: 1
Value: 7, Count: 1
Value: 9, Count: 1


In [9]:
list1 = [i for i in range(10)]
list1[3:5] = [0,0]
list2 = [str(i) for i in range(10)]
print(list1)
print(list2)
print(dict(zip(list1, list2)))
# list(zip(list1, list2))

[0, 1, 2, 0, 0, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
{0: '4', 1: '1', 2: '2', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9'}


In [19]:
values = [i for i in range(1000)]
count = 0
import time
start = time.time()
while count in values:
    count += 1
print(time.time() - start)

0.003668069839477539


In [3]:
max([m for m in lis])

ValueError: max() iterable argument is empty

In [9]:
test1 = {'a': 1, 'b': 2}
test2 = {'b': 3, 'c': 4}
test3 = {}
len(test3.keys())

0

#TODO
- Finalize Analyze (10-10:30)
- Steps (10:30 - 11)
- HDF5 Extraction (11 - 11:30)
- Image generation (11:30 - 12)

#TODO
- Prediction on new focus (12 - 12:30)
- Fluorescence extraction (12:30 - 1:30)
- Workup slides (1:30 - 2)

#TODO
- Histogram generation (11:45 - 12)
- Preferences
- Image Config
- Groupview
- Export/Import


In [10]:
import h5py
hdf5_path = "/Users/gh478/Documents/Research/multispectral-analysis/hdf5_data.h5"
f = h5py.File(hdf5_path, "r")

In [26]:
f['1'].dtype == 'O'

True

In [9]:
basename = os.path.splitext(os.path.basename(path))[0]
basename.replace("_", "")

'msautils'

In [21]:
import numpy as np

In [ ]:
test = np.array([1, 2, 3])
test2 = np.array([4, 5, 0])
var = 
np.divide(test, var, out=np.zeros(test), where=var!=0)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
# create two 2D test arrays
a = np.array([[1, 2, 1], [4, 5, 6]])
b = np.array([[1, 1, 2], [2, 2, 2]])
np.where(a >= b, a, 0)

array([[1, 2, 0],
       [4, 5, 6]])

In [14]:
def group_strlist(self, strlist: list[str]) -> dict[str, list[str]]:
    """
    Groups strings in strlist by common substrings separated by underscores.
    Returns a dictionary mapping substrings to lists of strings containing them.
    """
    groups = dict()
    groups_idx = []
    count = 0
    for i, s in enumerate(strlist):
        if s not in groups.keys():
            count += 1
            groups[s] = count
        groups_idx.append(groups[s])

    return groups_idx

test = ['aaa', 'aaa', 'bbb', 'aaa', 'bbb', 'ccc', 'ccc']
test = np.array(group_strlist(None, test))

In [1]:
test = [1,2,3]
test2 = test.copy()
test2

[1, 2, 3]

In [22]:
np.unique(test)

array([1, 2, 3])